// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.0
// source: order/order.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	OrderTrackingService_SubscribeToOrderUpdates_FullMethodName = "/order.v1.OrderTrackingService/SubscribeToOrderUpdates"
)

// OrderTrackingServiceClient is the client API for OrderTrackingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrderTrackingService streams real-time order status updates to subscribers.
type OrderTrackingServiceClient interface {
	SubscribeToOrderUpdates(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (OrderTrackingService_SubscribeToOrderUpdatesClient, error)
}

type orderTrackingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderTrackingServiceClient(cc grpc.ClientConnInterface) OrderTrackingServiceClient {
	return &orderTrackingServiceClient{cc}
}

func (c *orderTrackingServiceClient) SubscribeToOrderUpdates(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (OrderTrackingService_SubscribeToOrderUpdatesClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrderTrackingService_ServiceDesc.Streams[0], OrderTrackingService_SubscribeToOrderUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &orderTrackingServiceSubscribeToOrderUpdatesClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OrderTrackingService_SubscribeToOrderUpdatesClient interface {
	Recv() (*OrderStatusUpdate, error)
	grpc.ClientStream
}

type orderTrackingServiceSubscribeToOrderUpdatesClient struct {
	grpc.ClientStream
}

func (x *orderTrackingServiceSubscribeToOrderUpdatesClient) Recv() (*OrderStatusUpdate, error) {
	m := new(OrderStatusUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OrderTrackingServiceServer is the server API for OrderTrackingService service.
// All implementations must embed UnimplementedOrderTrackingServiceServer
// for forward compatibility
//
// OrderTrackingService streams real-time order status updates to subscribers.
type OrderTrackingServiceServer interface {
	SubscribeToOrderUpdates(*OrderRequest, OrderTrackingService_SubscribeToOrderUpdatesServer) error
	mustEmbedUnimplementedOrderTrackingServiceServer()
}

// UnimplementedOrderTrackingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOrderTrackingServiceServer struct {
}

func (UnimplementedOrderTrackingServiceServer) SubscribeToOrderUpdates(*OrderRequest, OrderTrackingService_SubscribeToOrderUpdatesServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeToOrderUpdates not implemented")
}
func (UnimplementedOrderTrackingServiceServer) mustEmbedUnimplementedOrderTrackingServiceServer() {}

// UnsafeOrderTrackingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderTrackingServiceServer will
// result in compilation errors.
type UnsafeOrderTrackingServiceServer interface {
	mustEmbedUnimplementedOrderTrackingServiceServer()
}

func RegisterOrderTrackingServiceServer(s grpc.ServiceRegistrar, srv OrderTrackingServiceServer) {
	s.RegisterService(&OrderTrackingService_ServiceDesc, srv)
}

func _OrderTrackingService_SubscribeToOrderUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OrderRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderTrackingServiceServer).SubscribeToOrderUpdates(m, &orderTrackingServiceSubscribeToOrderUpdatesServer{ServerStream: stream})
}

type OrderTrackingService_SubscribeToOrderUpdatesServer interface {
	Send(*OrderStatusUpdate) error
	grpc.ServerStream
}

type orderTrackingServiceSubscribeToOrderUpdatesServer struct {
	grpc.ServerStream
}

func (x *orderTrackingServiceSubscribeToOrderUpdatesServer) Send(m *OrderStatusUpdate) error {
	return x.ServerStream.SendMsg(m)
}

// OrderTrackingService_ServiceDesc is the grpc.ServiceDesc for OrderTrackingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderTrackingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.v1.OrderTrackingService",
	HandlerType: (*OrderTrackingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeToOrderUpdates",
			Handler:       _OrderTrackingService_SubscribeToOrderUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "order/order.proto",
}
